trigger:
  - master

jobs:
- job: BuildPushRedisACR
  variables:
    - template: vars/vars-global.yaml
  pool:
    vmImage: ${{ variables.vmImageName }}
  steps:
  - template: ${{ variables.ciBuildPath }} # Template reference
