trigger:
  - master

variables:
  - template: vars/vars-global.yaml

pool:
  vmImage: 'ubuntu-latest'

stages:
- template: ${{ variables.ciBuildPath }} # Template reference
- template: ${{ variables.cdDeployPath }} # Template reference

