trigger:
  - main

variables:
  - template: vars/vars-global.yaml

pool:
  vmImage: 'ubuntu-latest'


#- task: CopyFiles@2
#  inputs:
#  SourceFolder: './' # string. Source Folder.
#  Contents: "voteap_$(Build.BuildNumber)_$(datetime).yaml" # string. Required. Contents. Default: **.
#  TargetFolder: 'manifests/' # string. Required. Target Folder.

stages:
  jobs:
    - job: Create file naming variable
      steps:
        - bash: |
            #DATE=$(date '+%d/%m/%Y %H:%M:%S')
            #echo "##vso[task.setvariable variable=datetime;]$DATE"
            echo "##vso[task.setvariable variable=buildjob;]voteap_$(Build.BuildNumber)_${{ variable.datetime }}.yaml"
            rename azure-vote-all-in-one-redis.yaml ${buildjob}

    - template: ${{ variables.ciBuildPath }} # Template reference
    - template: ${{ variables.cdDeployPath }} # Template reference


