trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Install
  displayName: Build and push docker images
  variables:
    - template: vars/vars-global.yaml
- template: ${{ variables.ciBuildPath }} # Template reference
