parameters:
  - name: environmentAKS
    type: string
    default: 'bstanding76azurevotingapp'


stages:
  - stage: DeployRedisAndApp
    displayName: Deploy stage Redis and App
    dependsOn: BuildRedis
    jobs:
    - deployment: Deploy
      displayName: Deploy Job Redis
      environment: ${{ parameters.environmentAKS }}
      strategy:
        runOnce:
          deploy:
            steps:
            - task: KubernetesManifest@0
              displayName: Create imagePullSecret
              inputs:
                action: createSecret
                secretName: $(imagePullSecret)
                dockerRegistryEndpoint: ${{ variables.dockerRegistryServiceConnection }}

            - task: KubernetesManifest@0
              displayName: Deploy to Kubernetes cluster
              inputs:
                action: deploy
                manifests: |
                  $(Pipeline.Workspace)/manifests/voteap_$(Build.BuildNumber)_$(Get-Date -Format yyyyMMddhhmmss).yaml
#                  $(Pipeline.Workspace)/manifests/deployment-redis.yml
#                  $(Pipeline.Workspace)/manifests/service-redis.yml
                imagePullSecrets: |
                  ${{ variables.imagePullSecret }}
                containers: |
                  ${{ variables.dockerRegistryServiceConnection }}/${{ variables.imageRepositoryRedis }}:${{ variables.tag }}