# Agent VM image name
stages:
  - stage: Build
    displayName: Build and push stage redis
    jobs:
      - job: Build
    variables:
      - template: vars/vars-global.yaml
        displayName: Build
        pool:
          vmImage: ${{ vmImageName }}
        steps:
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              repository: ${{ imageRepositoryRedis }}
              dockerfile: ${{ dockerfilePath }}
              containerRegistry: ${{ dockerRegistryServiceConnection }}
              tags: |
                ${{ tag }}
  - stage: Build
    displayName: Build and push stage voting app
    jobs:
      - job: Build
    variables:
      - template: vars/vars-global.yaml
        displayName: Build
        pool:
          vmImage: ${{ vmImageName }}
        steps:
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              repository: ${{ imageRepositoryVotingApp }}
              dockerfile: ${{ dockerfilePath }}
              containerRegistry: ${{ dockerRegistryServiceConnection }}
              tags: |
                ${{ tag }}
