# File: templates/ci-build.yaml
stages:
  - stage: BuildRedis
    jobs:
    - job: Create file naming variable
      steps:
      - bash: |
          echo "##vso[task.setvariable variable=buildjob;]voteap_$(Build.BuildNumber)_${{ variable.datetime }}.yaml"
          rename azure-vote-all-in-one-redis.yaml ${buildjob}
    - job: Copy Deploy and Service file to manifests folder
      steps:
      - task: CopyFiles@2
        inputs:
          SourceFolder: './' # string. Source Folder.
          Contents: "voteap_$(Build.BuildNumber)_$(datetime).yaml" # string. Required. Contents. Default: **.
          TargetFolder: 'manifests/' # string. Required. Target Folder.
    - job: Build
      steps:
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          command: buildAndPush
          repository: ${{ variables.imageRepositoryRedis }}
          dockerfile: ${{ variables.dockerfilePathRedis }}
          containerRegistry: ${{ variables.dockerRegistryServiceConnection }}
          tags: |
            ${{ variables.tag }}
    - job: BuildVoteApp
      steps:
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          command: buildAndPush
          repository: ${{ variables.imageRepositoryVotingApp }}
          dockerfile: ${{ variables.dockerfilePathVoteApp }}
          containerRegistry: ${{ variables.dockerRegistryServiceConnection }}
          tags: |
            ${{ variables.tag }}
