# File: templates/ci-build.yaml
stages:
  - stage: BuildRedis
    jobs:
    - job: Build
      steps:
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          command: buildAndPush
          repository: ${{ variables.imageRepositoryRedis }}
          dockerfile: ${{ variables.dockerfilePathRedis }}
          containerRegistry: ${{ variables.dockerRegistryServiceConnection }}
          tags: |
            ${{ variables.tag }}
    - job: BuildVoteApp
      steps:
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          command: buildAndPush
          repository: ${{ variables.imageRepositoryVotingApp }}
          dockerfile: ${{ variables.dockerfilePathVoteApp }}
          containerRegistry: ${{ variables.dockerRegistryServiceConnection }}
          tags: |
            ${{ variables.tag }}
    - job: PublishBuildArtif
      steps:
      - publish: $(System.DefaultWorkingDirectory)/pipeline-artifacts/democi
        artifact: democi

