stages:
- stage: Build
  displayName: Build and push stage redis
  jobs:
    - job: Build
      pool:
        vmImage: ${{ variables.vmImageName }}
  variables:
    - template: vars/vars-global.yaml
  steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: ${{ variables.imageRepositoryRedis }}
        dockerfile: ${{ variables.dockerfilePath }}
        containerRegistry: ${{ variables.dockerRegistryServiceConnection }}
        tags: |
          ${{ variables.tag }}
- stage: Build
  displayName: Build and push stage voting app
  jobs:
    - job: Build
      pool:
        vmImage: ${{ variables.vmImageName }}
  variables:
    - template: vars/vars-global.yaml
  steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: ${{ variables.imageRepositoryVotingApp }}
        dockerfile: ${{ variables.dockerfilePath }}
        containerRegistry: ${{ variables.dockerRegistryServiceConnection }}
        tags: |
          ${{ variables.tag }}